AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:

  EnvironmentTable:
    Type: AWS::DynamoDB::Table
    Properties:
     #TODO: change ddb table names to have region prefix passed in as a resource
     TableName: Environments
     AttributeDefinitions:
       - AttributeName: accountIdCluster
         AttributeType: S
       - AttributeName: environmentName
         AttributeType: S
       - AttributeName: accountId
         AttributeType: S
       - AttributeName: cluster
         AttributeType: S
     KeySchema:
       - AttributeName: "accountIdCluster"
         KeyType: HASH
       - AttributeName: "environmentName"
         KeyType: RANGE
     ProvisionedThroughput:
       ReadCapacityUnits: 15
       WriteCapacityUnits: 15
     GlobalSecondaryIndexes:
       -
         IndexName: "environmentClusterIndex"
         KeySchema:
           - AttributeName: "accountId"
             KeyType: HASH
           - AttributeName: "cluster"
             KeyType: RANGE
         Projection:
           ProjectionType: "KEYS_ONLY"
         ProvisionedThroughput:
           ReadCapacityUnits: 15
           WriteCapacityUnits: 15

  EnvironmentRevisionTable:
    Type: AWS::DynamoDB::Table
    Properties:
     #TODO: change ddb table names to have region prefix passed in as a resource
      TableName: EnvironmentRevisions
      AttributeDefinitions:
        - AttributeName: accountIdClusterEnvironmentName
          AttributeType: S
        - AttributeName: environmentRevisionId
          AttributeType: S
      KeySchema:
        - AttributeName: "accountIdClusterEnvironmentName"
          KeyType: HASH
        - AttributeName: "environmentRevisionId"
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 15
        WriteCapacityUnits: 15

  DataServiceHandler:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java8
      CodeUri: null
      Handler: com.amazonaws.blox.dataservice.LambdaHandler
      MemorySize: 512
      Timeout: 30
      Policies:
      - AmazonDynamoDBFullAccess # TODO: scope down permissions

Outputs:
  DataService:
    Description: Name of Data service handler function
    Value:
      Ref: DataServiceHandler
    Export:
      Name: DataServiceHandler
  DataServiceArn:
    Description: Arn of Data service handler function
    Value:
      Fn::GetAtt: [DataServiceHandler, Arn]
    Export:
      Name: DataServiceHandlerArn
