AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
     #TODO: change ddb table names to have region prefix passed in as a resource
     TableName: Environments
     AttributeDefinitions:
       - AttributeName: environmentId
         AttributeType: S
       - AttributeName: environmentVersion
         AttributeType: S
       - AttributeName: cluster
         AttributeType: S
     KeySchema:
       - AttributeName: "environmentId"
         KeyType: HASH
       - AttributeName: "environmentVersion"
         KeyType: RANGE
     GlobalSecondaryIndexes:
       -
         IndexName: "environment-cluster-index"
         KeySchema:
           -
             AttributeName: "cluster"
             KeyType: "HASH"
         Projection:
           ProjectionType: "KEYS_ONLY"
         ProvisionedThroughput:
           ReadCapacityUnits: 15
           WriteCapacityUnits: 15
     ProvisionedThroughput:
       ReadCapacityUnits: 15
       WriteCapacityUnits: 15

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
     #TODO: change ddb table names to have region prefix passed in as a resource
     TableName: EnvironmentsLatestVersion
     AttributeDefinitions:
       - AttributeName: environmentId
         AttributeType: S
       - AttributeName: environmentVersion
         AttributeType: S
     KeySchema:
       - AttributeName: "environmentId"
         KeyType: HASH
       - AttributeName: "environmentVersion"
         KeyType: RANGE
     ProvisionedThroughput:
       ReadCapacityUnits: 15
       WriteCapacityUnits: 15