AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Scheduler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.amazonaws.blox.scheduling.scheduler.SchedulerEntrypoint
      Runtime: java8
      CodeUri: ../build/distributions/scheduling-manager.zip
      Timeout: 60
      MemorySize: 512
      Tracing: PassThrough
      Policies:
        - AWSXrayWriteOnlyAccess

  Manager:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.amazonaws.blox.scheduling.manager.ManagerEntrypoint
      Runtime: java8
      CodeUri: ../build/distributions/scheduling-manager.zip
      Timeout: 60
      MemorySize: 512
      Tracing: PassThrough
      Policies:
        - AWSLambdaFullAccess
      Environment:
        Variables:
          scheduler_function_name: !Ref Scheduler

  Reconciler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.amazonaws.blox.scheduling.reconciler.ReconcilerEntrypoint
      Runtime: java8
      CodeUri: ../build/distributions/scheduling-manager.zip
      Timeout: 60
      MemorySize: 512
      Tracing: Active
      Policies:
        - AWSLambdaFullAccess
      Environment:
        Variables:
          manager_function_name: !Ref Manager

  ReconcilerTrigger:
    Type: AWS::Events::Rule
    Properties:
      Description: Periodic trigger for Scheduler Reconciliation
      ScheduleExpression: "rate(1 minute)"
      Targets:
        - Id: !Ref Reconciler
          Arn:
            Fn::GetAtt: [Reconciler, Arn]

  ReconcilerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref Reconciler
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt: [ReconcilerTrigger, Arn]

  ProcessDeploymentRecords:
    Type: AWS::Serverless::Function
    Properties:
       Handler: com.amazonaws.blox.scheduling.stream.processor.StreamProcessorHandler
       Runtime: java8
       CodeUri: ../build/distributions/scheduling-manager.zip
       Timeout: 60
       MemorySize: 256
       Policies:
       - Version: '2012-10-17' # Policy Document
         Statement:
           - Effect: Allow
             Action:
                - dynamodb:DescribeStream
                - dynamodb:GetRecords
                - dynamodb:GetShardIterator
                - dynamodb:ListStreams
             Resource: !Sub
               'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/Deployments/stream/*'
           - Effect: Allow
             Action:
               - logs:CreateLogGroup
               - logs:CreateLogStream
               - logs:PutLogEvents
             Resource: !Sub
               'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*'
       Events:
         DeploymentRecordEvent:
           Type: DynamoDB
           Properties:
             Stream: !Sub
               arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/Deployments/stream/2017-08-23T00:09:35.158
             StartingPosition: TRIM_HORIZON
             BatchSize: 10
